version: 2
jobs:
  build:
    machine: true
    environment:
      # This revision is 10.15.3 but actually true 10.15.3 failed in official node CI, so this is not true 10.15.3.
      NODE_REVISION: 156e4c8e89616a3f128453ff43cac5103a8226fa
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t node-build-env .
      - run:
          name: Clone node and checkout
          command: |
            git clone https://github.com/nodejs/node.git
            cd node
            git checkout $NODE_REVISION
      - run:
          name: "Working test - build node"
          command: |
            docker run --rm -i -v $PWD/node:/build/node node-build-env /bin/bash << EOF
            set -xeu
            cd /build/node
            ./configure
            make -j2 V=
            PARALLEL_ARGS='--flaky-tests=skip' make -j1 test
            EOF
