name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t node-build-env .
    - name: Clone node and checkout
      run: |
        git clone https://github.com/nodejs/node.git
        cd node
        git checkout $NODE_REVISION
      env:
        NODE_REVISION: v12.19.0
    - name: "Working test - build node"
      run: |
        docker run --rm -i -v $PWD/node:/build/node node-build-env /bin/bash << EOF
        set -xeu
        cd /build/node
        ./configure
        make -j2 V=
        PARALLEL_ARGS='--flaky-tests=skip' make -j1 test
        EOF
